#FROM postgres:latest
#
#ENV POSTGRES_DB gilgoblin
#ENV POSTGRES_USER admin
#ENV POSTGRES_PASSWORD gilgoblin
#
#COPY ./resources/sql_creation_script.sql /docker-entrypoint-initdb.d/sql_creation_script.sql
#
#EXPOSE 5432
