FROM postgres:alpine

# RUN apk add --no-cache postgresql-client

# WORKDIR /docker-entrypoint-initdb.d

# COPY /resources/pg_dump.sql /docker-entrypoint-initdb.d/pg_dump.sql

# RUN chmod +x /docker-entrypoint-initdb.d/

EXPOSE 5432